version: '3'

services:
  rabbitmq-server:
    container_name: rabbitmq-server
    image: "rabbitmq:3.12-management-alpine"
    hostname: "rabbitmq-server"
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    networks:
      - rabbit-network
  consumer:
    container_name: consumer
    build: .
    restart: always
    depends_on:
      - rabbitmq-server
    env_file:
      - .env
    networks:
      - rabbit-network

networks:
  rabbit-network:
    driver: bridge
